import { db } from "./db";
import { categories, axioms, axiomDependencies, axiomEnables, perspectives } from "@shared/schema";

async function seed() {
  console.log("Seeding database...");

  const catData = [
    { slug: "00_System", label: "System", sortOrder: 0 },
    { slug: "01_Axioms", label: "Axioms", sortOrder: 1 },
    { slug: "01_Ontological", label: "Ontological Proofs", sortOrder: 2 },
    { slug: "02_Definitions", label: "Definitions", sortOrder: 3 },
    { slug: "02_Modality", label: "Modality & Necessity", sortOrder: 4 },
    { slug: "03_Coherence", label: "Coherence & Order", sortOrder: 5 },
    { slug: "03_Lemmas", label: "Lemmas", sortOrder: 6 },
    { slug: "03_Operators", label: "Operators", sortOrder: 7 },
    { slug: "04_Observation", label: "Observation", sortOrder: 8 },
    { slug: "04_Theorems", label: "Theorems", sortOrder: 9 },
    { slug: "05_Necessary", label: "Necessary Axioms", sortOrder: 10 },
    { slug: "06_Agency", label: "Agency & Will", sortOrder: 11 },
    { slug: "07_Evidence", label: "Evidence & External", sortOrder: 12 },
    { slug: "07_Personal", label: "Personal & Experiential", sortOrder: 13 },
    { slug: "09_Papers", label: "Papers", sortOrder: 14 },
    { slug: "10_Maps", label: "Maps", sortOrder: 15 },
    { slug: "11_External", label: "External Standards", sortOrder: 16 },
    { slug: "Apologetics", label: "Apologetics", sortOrder: 17 },
    { slug: "Axiom_Explanation", label: "Axiom Explanations", sortOrder: 18 },
    { slug: "Consciousness", label: "Consciousness", sortOrder: 19 },
    { slug: "Core_Theorems", label: "Core Theorems", sortOrder: 20 },
    { slug: "Eschatology", label: "Eschatology", sortOrder: 21 },
    { slug: "Existence_Ontology", label: "Existence Ontology", sortOrder: 22 },
    { slug: "Foundational_Papers", label: "Foundational Papers", sortOrder: 23 },
    { slug: "God_Nature", label: "God & Nature", sortOrder: 24 },
    { slug: "Human_Soul", label: "Human Soul", sortOrder: 25 },
    { slug: "Information_Theory", label: "Information Theory", sortOrder: 26 },
    { slug: "LOVE_Pastoral", label: "Love & Pastoral", sortOrder: 27 },
    { slug: "MATH", label: "Math Framework", sortOrder: 28 },
    { slug: "Math_Framework", label: "Math Framework (Adv)", sortOrder: 29 },
    { slug: "Prosecuted_Axioms", label: "Prosecuted Axioms", sortOrder: 30 },
    { slug: "Salvation_Grace", label: "Salvation & Grace", sortOrder: 31 },
    { slug: "Sin_Problem", label: "Sin Problem", sortOrder: 32 },
    { slug: "Trinity", label: "Trinity", sortOrder: 33 },
    { slug: "Type", label: "Type Theory", sortOrder: 34 },
  ];

  for (const c of catData) {
    await db.insert(categories).values(c).onConflictDoNothing();
  }

  const axiomData = [
    {
      nodeId: "A1.1",
      title: "Existence",
      chainPosition: 1,
      objectType: "Axiom",
      stage: "1",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 7,
      conflicts: 0,
      formalStatement: "Something exists rather than nothing.",
      intendedMeaning: "The most basic, self-evident starting point. Any denial of existence presupposes a denier that exists. This is the bedrock on which the entire chain rests.",
      notClaiming: ["Not claiming what exists", "Not claiming how many things exist"],
      commonSenseTruth: "Something is here. You're reading this, so at least something exists.",
      commonSenseAccepted: "Universally accepted. Even the most radical skeptic cannot deny their own existence without contradicting themselves.",
      commonSenseExplanation: "Try to imagine nothing at all—no space, no time, no thoughts. You can't, because you're already something doing the imagining. Existence is the one thing you can never escape.",
      physicsMapping: "Observable universe",
      theologyMapping: "I AM (Exodus 3:14)",
      consciousnessMapping: "Cogito ergo sum",
      quantumMapping: "Vacuum energy",
      scriptureMapping: "Genesis 1:1",
      evidenceMapping: "Self-evident",
      informationMapping: "Non-null set",
      categorySlug: "Existence_Ontology",
    },
    {
      nodeId: "A1.2",
      title: "Distinction",
      chainPosition: 2,
      objectType: "Axiom",
      stage: "1",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 7,
      conflicts: 0,
      formalStatement: "For anything to be describable or knowable, it must be distinguishable from something else.",
      intendedMeaning: "Distinction is the minimal bridge between 'something exists' and 'something can be identified.' Without it, the universe is a featureless, uninformative singularity. This supports later claims about information and measurement without committing to a specific physics.",
      notClaiming: ["Not that all distinctions are binary", "Not that all distinctions are human-made; the claim is about reality, not labels"],
      commonSenseTruth: "You can tell one thing from another. Light is different from dark, hot is different from cold.",
      commonSenseAccepted: "Universally accepted. The ability to distinguish is the foundation of all perception and language.",
      commonSenseExplanation: "Imagine a world where nothing was different from anything else. No color, no shape, no up or down. It would be like a TV screen showing only one solid color forever. Nothing could happen, nothing could be known, because there would be no 'this' versus 'that.' Distinction is the first step from 'something exists' to 'something can be identified.'",
      commonSenseVariable: "Existence requires distinguishability",
      physicsMapping: "Observables / Contrast",
      theologyMapping: "Genesis 1 ordering",
      consciousnessMapping: "Qualia",
      quantumMapping: "Quantum distinguishability",
      scriptureMapping: "Genesis 1:4 (light/dark)",
      evidenceMapping: "QM experiments",
      informationMapping: "Distinction as bit",
      physicsLayer: "Quantum mechanics is fundamentally a theory of distinguishability. Orthogonality principle: Two states |ψ⟩ and |φ⟩ are perfectly distinguishable iff ⟨ψ|φ⟩ = 0. Measurement postulate: Observable A has distinct eigenvalues corresponding to distinguishable outcomes. Pauli Exclusion: No two fermions can occupy the same quantum state → fermions MUST be distinguished by at least one quantum number.",
      mathLayer: "Shannon entropy requires distinguishable outcomes: H(X) = -Σ p(x) log p(x). If all outcomes are indistinguishable, H(X) = 0. Spencer-Brown's Laws of Form: The mark (distinction) is the primitive operation from which all logic derives. Yoneda Lemma: An object is determined by its relationships (distinctions) with all other objects.",
      prosecutorDefense: "The court has established that existence (A1.1) is the non-negotiable starting point. We now demonstrate that existence without distinction is a logical impossibility for any describable, knowable, or structured reality. The defendant, any worldview that denies the fundamental nature of distinction, is charged with undermining the very basis of information, measurement, and knowledge.",
      crossExaminations: [
        { target: "The Skeptic", text: "You may claim distinctions are merely human constructs. But consider: to even make that claim, you must distinguish your position from its opposite. Your denial is self-refuting." },
        { target: "The Physicist", text: "Your entire discipline rests on distinguishable states. Quantum mechanics defines measurement as the extraction of distinguishable outcomes. Without distinction, there are no observables, no eigenvalues, no physics." },
        { target: "The Materialist", text: "Every particle has properties that distinguish it from others. Even 'identical' particles are distinguished by their quantum numbers. Material reality is a web of distinctions." }
      ],
      verdict: "Distinction is not merely a useful concept; it is a logical necessity for any world that can be described, known, or measured. Its denial is self-refuting. The axiom stands as the bridge from raw existence to structured reality.",
      defeatConditions: ["Self-refuting to deny. Any attempt to claim 'distinctions don't exist' requires distinguishing 'no distinctions' from 'distinctions exist' and making a claim distinct from its negation. Denial proves the axiom."],
      standardObjections: [
        { objection: "Reality is continuous, not discrete", response: "Bekenstein bound proves finite bits per region; real numbers are approximations of discrete substrates. Planck scale sets minimum distinguishable length." },
        { objection: "Nats are more natural than bits (base e vs base 2)", response: "Bit is the minimal distinction (two states). Nats use continuous e-base which presupposes reals. Bits are operationally primary—every measurement resolves a binary question." },
        { objection: "Qubits supersede classical bits", response: "Qubits are measured in bits upon observation (Born rule). Superposition collapses to binary outcomes. The bit remains the unit of extracted information." }
      ],
      defenseSummary: "Existence requires distinguishability. Built on A1.1 (Existence). Enables A1.3 (Information Primacy) and D1.1 (Information Definition).",
      collapseAnalysis: "If A1.2 fails: No information (information requires distinction), No measurement (nothing to measure against), No physics (no observables), No knowledge (nothing to know), No language (no meaning without difference). Distinction is the bridge from 'something exists' to 'something can be identified.'",
      sourceFiles: ["01_Axioms/_sources/Theophysics_Axiom_Spine_Master.xlsx", "01_Axioms/AX-002 Distinction.md"],
      categorySlug: "Existence_Ontology",
    },
    {
      nodeId: "A1.3",
      title: "Information Primacy",
      chainPosition: 3,
      objectType: "Axiom",
      stage: "1",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 7,
      conflicts: 0,
      formalStatement: "Information is the most fundamental category of reality. Matter, energy, and spacetime are emergent from information.",
      intendedMeaning: "If distinction exists (A1.2), then information exists. The bit is the minimal unit of distinction. All physical quantities can be expressed as information. This is the 'It from Bit' hypothesis formalized.",
      commonSenseTruth: "Everything around you is made of patterns and information—from your DNA to the stars.",
      commonSenseAccepted: "Increasingly accepted in modern physics and philosophy.",
      physicsMapping: "It from Bit (Wheeler)",
      theologyMapping: "John 1:1 (Logos/Word)",
      consciousnessMapping: "Integrated Information",
      quantumMapping: "Quantum information theory",
      scriptureMapping: "John 1:1",
      evidenceMapping: "Shannon 1948",
      informationMapping: "Information as primitive",
      categorySlug: "Information_Theory",
    },
    {
      nodeId: "A1.4",
      title: "Logical Precedence",
      chainPosition: 4,
      objectType: "Axiom",
      stage: "1",
      status: "Pending",
      crRating: "Critical",
      bridgeCount: 5,
      conflicts: 0,
      formalStatement: "Logic is prior to and independent of physical reality.",
      commonSenseTruth: "The rules of logic work whether or not anyone is around to think about them.",
      physicsMapping: "Mathematical consistency",
      theologyMapping: "Logos as rational order",
      categorySlug: "Existence_Ontology",
    },
    {
      nodeId: "D1.1",
      title: "Information Definition",
      chainPosition: 5,
      objectType: "Definition",
      stage: "1",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 7,
      conflicts: 0,
      formalStatement: "Information ≡ a distinction that makes a difference (Bateson) + can be encoded, stored, transmitted, and measured.",
      commonSenseTruth: "Information is any pattern that tells you something—like a stop sign telling you to stop.",
      categorySlug: "02_Definitions",
    },
    {
      nodeId: "D1.2",
      title: "Bit Definition",
      chainPosition: 6,
      objectType: "Definition",
      stage: "1",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 7,
      conflicts: 0,
      formalStatement: "Bit ≡ min( distinction(binary) )",
      intendedMeaning: "The bit is the minimal unit of distinction. A single binary choice: yes/no, on/off, 0/1.",
      commonSenseTruth: "A bit is the simplest possible piece of information—a yes or no answer.",
      physicsMapping: "Observables / Contrast",
      theologyMapping: "Genesis 1:4 (light/dark)",
      consciousnessMapping: "Qualia",
      quantumMapping: "Quantum distinguishability",
      scriptureMapping: "Genesis 1:4",
      evidenceMapping: "Shannon 1948",
      informationMapping: "Distinction as bit",
      categorySlug: "02_Definitions",
    },
    {
      nodeId: "A2.1",
      title: "Substrate Requirement",
      chainPosition: 7,
      objectType: "Axiom",
      stage: "2",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 6,
      conflicts: 0,
      formalStatement: "Information requires a substrate to exist. There is no 'free-floating' information.",
      commonSenseTruth: "Information has to live somewhere—a book, a brain, a computer, something.",
      categorySlug: "01_Axioms",
    },
    {
      nodeId: "A2.2",
      title: "Self-Grounding",
      chainPosition: 8,
      objectType: "Axiom",
      stage: "2",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 6,
      conflicts: 0,
      formalStatement: "The ultimate substrate must be self-grounding (not dependent on another substrate).",
      commonSenseTruth: "If there's no solid foundation for reality's information, then everything is just floating around without any real meaning or stability.",
      commonSenseAccepted: "The idea of needing an anchor/foundation for stability is intuitive.",
      commonSenseExplanation: "Imagine a giant airship floating in the sky, and that airship is reality. What's holding it still? If it has anchors, but those anchors are just tied to other floating airships, and those are tied to others, and so on forever, then the whole thing is just drifting. This axiom says that for reality to be truly stable, it needs an anchor that isn't floating.",
      commonSenseVariable: "NOT(Self_Grounding_Substrate) IMPLIES NOT(Information_Anchored)",
      prosecutorDefense: "Without a self-grounding substrate, information lacks ultimate stability and therefore causal efficacy. Meaning becomes transient, structure becomes arbitrary, and reality itself becomes unanchored, vulnerable to arbitrary collapse or alteration.",
      crossExaminations: [
        { target: "The Scientist", text: "Your scientific enterprise, with its quest for stable laws and reproducible results, implicitly relies on the stability of information. If the laws of physics are not ultimately anchored in an unchangeable ground, then your entire edifice of knowledge is built on sand." },
        { target: "The Nihilist", text: "You claim meaning is illusory. This axiom explains why such a worldview is inevitable if you deny the self-grounding substrate. Without an ultimate anchor, meaning can indeed appear arbitrary and unstable." },
        { target: "The Dependent Substrate Advocate", text: "If the informational substrate is itself dependent on something else, then the information it carries is also dependent. This creates an infinite regress where no information is ever truly anchored." }
      ],
      verdict: "The Logos Field (χ), as the self-grounding informational substrate, provides the immutable anchor for all existence, ensuring the stability and coherence that prevents reality from dissolving into chaos.",
      categorySlug: "01_Axioms",
    },
    {
      nodeId: "D2.1",
      title: "Logos Field Definition",
      chainPosition: 9,
      objectType: "Definition",
      stage: "2",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 7,
      conflicts: 0,
      formalStatement: "The Logos Field (χ) operates to continuously minimize the total Kolmogorov Complexity of the universe's description.",
      commonSenseTruth: "Reality has an underlying pattern-maker that keeps things organized and meaningful.",
      categorySlug: "02_Definitions",
    },
    {
      nodeId: "LN2.1",
      title: "Information Anchor Necessity",
      chainPosition: 10,
      objectType: "Lemma",
      stage: "2",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 5,
      conflicts: 0,
      formalStatement: "Without self-grounding substrate, information has no anchor.",
      commonSenseTruth: "If there's no solid foundation for reality's information, then everything is just floating around without any real meaning or stability.",
      categorySlug: "03_Lemmas",
    },
    {
      nodeId: "D3.1",
      title: "Coherence Functional Definition",
      chainPosition: 18,
      objectType: "Definition",
      stage: "3",
      status: "Validated",
      crRating: "Critical",
      bridgeCount: 7,
      conflicts: 0,
      formalStatement: "Coherence C[χ] = measure of organized information density",
      intendedMeaning: "Coherence is a measurable property of the Logos Field that quantifies how well-organized and dense with meaning it is.",
      commonSenseTruth: "'Coherence' is just a fancy word for how well-organized and dense with meaning the Logos Field is, like a really well-written book with lots of packed information.",
      commonSenseAccepted: "Requires analogy/explanation, but the idea of 'well-organized information' is intuitive.",
      commonSenseExplanation: "Imagine trying to understand something. Some things are easy to understand because they're clear and well-organized, like a well-written instruction manual. Other things are confusing, like random words. Coherence is just how clear, well-organized, and packed with meaning something is.",
      commonSenseVariable: "Coherence = Organized_Information_Density",
      physicsMapping: "Low Entropy",
      theologyMapping: "1 Cor 14:33 order",
      consciousnessMapping: "Organized activity",
      quantumMapping: "Quantum coherence",
      scriptureMapping: "1 Cor 14:33 order",
      evidenceMapping: "Shannon 1948",
      informationMapping: "Signal vs noise",
      prosecutorDefense: "The court has established the necessity of organization for meaningful information (A3.1) and the Logos Field's drive to minimize descriptive complexity (A3.2). We now provide a formal, measurable definition for 'Coherence' (C[χ]) as the measure of this success.",
      crossExaminations: [
        { target: "The Skeptic", text: "You may claim 'coherence' is a subjective, undefinable concept. This definition makes it objective: it's a measure of organized information density. Consider a highly structured program versus random data. The difference is objectively measurable." },
        { target: "The Physicist", text: "You are familiar with entropy and information density. Coherence is the positive measure of effective, organized information density, related to negentropy." },
        { target: "The Materialist", text: "You must confront that reality is not just 'stuff,' but organized information. Coherence quantifies the quality of this organization." }
      ],
      verdict: "Coherence is not an abstract philosophical concept; it is a measurable property of the Logos Field. It quantifies the degree to which information is organized, compressed, and packed with meaning.",
      categorySlug: "03_Coherence",
    },
  ];

  for (const a of axiomData) {
    await db.insert(axioms).values(a).onConflictDoNothing();
  }

  const depData = [
    { axiomNodeId: "A1.2", dependsOnNodeId: "A1.1", relationship: "assumes", description: "Something must exist before distinctions can be made" },
    { axiomNodeId: "A1.3", dependsOnNodeId: "A1.2", relationship: "assumes", description: "Distinction IS information; the minimal bit" },
    { axiomNodeId: "A1.4", dependsOnNodeId: "A1.3", relationship: "assumes" },
    { axiomNodeId: "D1.1", dependsOnNodeId: "A1.2", relationship: "assumes", description: "Formal definition requires distinction" },
    { axiomNodeId: "D1.2", dependsOnNodeId: "D1.1", relationship: "assumes" },
    { axiomNodeId: "A2.1", dependsOnNodeId: "A1.3", relationship: "assumes" },
    { axiomNodeId: "A2.2", dependsOnNodeId: "A2.1", relationship: "assumes" },
    { axiomNodeId: "D2.1", dependsOnNodeId: "A2.2", relationship: "assumes" },
    { axiomNodeId: "LN2.1", dependsOnNodeId: "A2.2", relationship: "assumes" },
    { axiomNodeId: "D3.1", dependsOnNodeId: "A1.3", relationship: "assumes" },
  ];

  for (const d of depData) {
    await db.insert(axiomDependencies).values(d).onConflictDoNothing();
  }

  const enableData = [
    { axiomNodeId: "A1.1", enablesNodeId: "A1.2", description: "Existence enables distinction" },
    { axiomNodeId: "A1.2", enablesNodeId: "A1.3", description: "Distinction IS information; the minimal bit" },
    { axiomNodeId: "A1.2", enablesNodeId: "D1.1", description: "Formal definition requires distinction" },
    { axiomNodeId: "A1.3", enablesNodeId: "A1.4" },
    { axiomNodeId: "A1.3", enablesNodeId: "A2.1" },
    { axiomNodeId: "A2.1", enablesNodeId: "A2.2" },
    { axiomNodeId: "A2.2", enablesNodeId: "D2.1" },
    { axiomNodeId: "A2.2", enablesNodeId: "LN2.1" },
    { axiomNodeId: "D1.1", enablesNodeId: "D1.2" },
    { axiomNodeId: "D3.1", enablesNodeId: "D3.2", description: "Self-Interaction Potential" },
  ];

  for (const e of enableData) {
    await db.insert(axiomEnables).values(e).onConflictDoNothing();
  }

  const perspData = [
    { axiomNodeId: "A1.2", name: "Non-Theistic Metaphysical Realism", quote: "Distinction is a fundamental, brute structural feature of reality. Things are distinct because that is the nature of the informational-mathematical matrix.", assessment: "This view affirms the axiom as a necessary structural feature. The tension is whether distinction is ultimate or derived. The non-theist model treats it as ultimate/brute, while Theophysics treats it as derived from the Trinity (A7.2).", sortOrder: 0 },
    { axiomNodeId: "A1.2", name: "Advaita Vedanta / Monism", quote: "Ultimate reality is undifferentiated (Brahman). Distinctions are a lower-level, persistent illusion (Maya).", assessment: "This challenges the axiom's ultimate status but accepts its provisional necessity. To claim Brahman is 'undifferentiated' requires a distinction between 'undifferentiated' and 'differentiated.' Thus, distinction appears logically prior to any claim about unity.", sortOrder: 1 },
    { axiomNodeId: "A1.2", name: "Structural Realism", quote: "Only the distinctions (structures) are real; the underlying 'stuff' is not.", assessment: "Near-perfect alignment with A1.2. It elevates distinction to the status of ontological primitive.", sortOrder: 2 },
  ];

  for (const p of perspData) {
    await db.insert(perspectives).values(p).onConflictDoNothing();
  }

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
